import 'package:flutter/material.dart';

const Color kPrimaryColor = Color(0xFFFF0000);
const Color kPrimaryColor2 = Color(0xFFFF6666);
const Color kPrimaryColor3 = Color(0xFFFF9999);
const Color kPrimaryColor4 = Color(0xFFFFCCCC);
const Color kPrimaryColor5 = Color(0xFFFFF5F5);
const Color kSecondaryColor = Color(0xFF3A405A);
const Color kSecondaryColor2 = Color(0xFF61667B);
const Color kSecondaryColor3 = Color(0xFF898C9C);
const Color kSecondaryColor4 = Color(0xFFB0B3BD);
const Color kSecondaryColor5 = Color(0xFFEBECEF);
const Color kTertiaryColor = Color(0xFF2660A4);
const Color kTertiaryColor2 = Color(0xFF5180B6);
const Color kTertiaryColor3 = Color(0xFF7DA0C8);
const Color kTertiaryColor4 = Color(0xFFA8BFDB);
const Color kTertiaryColor5 = Color(0xFFE9EFF6);
const Color kWhiteColor = Color(0xFFFFFFFF);
const Color kBlackColor = Color(0xFF000000);
const Color kLightGreenColor = Color(0xFFE9FCF8);
const Color kLightPurpleColor = Color(0xFFF2E9FC);
